version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      replicas: 4
